general:
steps:
  mtaBuild:
    buildTarget: 'CF'
 cloudFoundryDeploy:
    deployTool: 'mtaDeployPlugin'
    deployType: 'standard'
    cloudFoundry:
      org: '2f317a0ftrial'
      space: 'dev'
      credentialsId: 'CF_CREDENTIALSID'
